version: "3.7"

networks:
  damabox:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     config:
      - subnet: ${SUBNET:-10.5.0.0/24}

services:

  bind:
    image: cytopia/bind:0.15
    restart: always
    hostname: bind
    dns:
      - 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - "EXTRA_HOSTS=${BIND_EXTRA_HOSTS:-}"
      - "WILDCARD_DNS=${BIND_TLD_SUFFIX:-local}=127.0.0.1"
      - "DNS_FORWARDER=${BIND_DNS_RESOLVER:-8.8.8.8,8.8.4.4}"
    extra_hosts:
      docker.for.lin.host.internal: ${GATEWAY:-10.5.0.1}
      docker.for.lin.localhost: ${GATEWAY:-10.5.0.1}
    networks:
      damabox:
        ipv4_address: ${BIND_IP:-10.5.0.10}

  nginx:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-nginx
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: nginx
    ports:
     - ${NGINX_HTTP_PORT:-80}:80
     - ${NGINX_HTTPS_PORT:-443}:443
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
     - ${PUBLIC_DATA_DIR:-./data/www}:/app
     - ${SSH_KEYS:-./data/ssh-keys}:/root/.ssh
     - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./config/nginx/sites-available:/etc/nginx/conf.d
    networks:
      - damabox
    depends_on:
      - bind
      
  php-5.6:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5.6
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-5.6
    volumes:
      - ${PUBLIC_DATA_DIR:-./data/www}:/app
      - ${SSH_KEYS:-./data/ssh-keys}:/home/damabox/.ssh
      - ./config/php/5.6:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - damabox
    depends_on:
      - nginx

  php-7.0:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.0
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-7.0
    volumes:
      - ${PUBLIC_DATA_DIR:-./data/www}:/app
      - ${SSH_KEYS:-./data/ssh-keys}:/home/damabox/.ssh
      - ./config/php/7.0:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - damabox
    depends_on:
      - nginx

  php-7.1:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.1
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-7.1
    volumes:
      - ${PUBLIC_DATA_DIR:-./data/www}:/app
      - ${SSH_KEYS:-./data/ssh-keys}:/home/damabox/.ssh
      - ./config/php/7.1:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - damabox
    depends_on:
      - nginx

  php-7.2:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.2
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-7.2
    volumes:
      - ${PUBLIC_DATA_DIR:-./data/www}:/app
      - ${SSH_KEYS:-./data/ssh-keys}:/home/damabox/.ssh
      - ./config/php/7.2:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - damabox
    depends_on:
      - nginx
  
  php-7.3:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7.3
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: php-7.3
    volumes:
      - ${PUBLIC_DATA_DIR:-./data/www}:/app
      - ${SSH_KEYS:-./data/ssh-keys}:/home/damabox/.ssh
      - ./config/php/7.3:/usr/local/etc/php
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    networks:
      - damabox
    depends_on:
      - nginx

  mysql:
    image: ${MYSQL_TYPE:-mysql}:${MYSQL_VERSION:-5.7}
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-damabox}
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${MYSQL_DATA_DIR:-./data/db}/${MYSQL_TYPE:-mysql}/${MYSQL_VERSION:-5.7}:/var/lib/mysql
      - ${SSH_KEYS:-./data/ssh-keys}:/root/.ssh
      - ./config/db/${MYSQL_TYPE:-mysql}:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - damabox
    depends_on:
      - bind
  
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.2}
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: postgres
    ports:
      - ${POSTGRES_PORT:-8080}:8080
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-damabox}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-damabox}
      - PGDATA=/databases
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${POSTGRES_DATA_DIR:-./data/db/postgres}/${POSTGRES_VERSION:-11.2}:/databases
      - ${SSH_KEYS:-./data/ssh-keys}:/root/.ssh
      - ./config/db/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    entrypoint: "docker-entrypoint.sh -c 'config_file=/var/lib/postgresql/data/postgresql.conf'"
    networks:
      - damabox
    depends_on:
      - bind

  redis:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-redis
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-damabox}
    volumes:
      - ${REDIS_DATA_DIR:-./data/db/redis}:/data
      - ${SSH_KEYS:-./data/ssh-keys}:/root/.ssh
      - ./config/db/redis:/redis_conf
    command: sh /run.sh
    networks:
      - damabox
    depends_on:
      - bind

  mongo:
    image: mongo:${MONGO_VERSION:-4.2.0-bionic}
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: mongo
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-damabox}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-damabox}
    volumes:
      - ${MONGO_DATA_DIR:-./data/db/mongodb}:/data/db
      - ${SSH_KEYS:-./data/ssh-keys}:/root/.ssh
    networks:
      - damabox
    depends_on:
      - bind

  firebird-2.5:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-firebird2.5
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: firebird-2.5
    ports:
      - ${FIREBIRD25_PORT:-3050}:3050
      - ${HQBIRD25_PANEL_PORT:-8082}:8082
      - ${HQBIRD25_LICENSE_PORT:-8765}:8765
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${FIREBIRD25_DATA_DIR:-./data/db/firebird/2.5}:/databases
      - ${SSH_KEYS:-./data/ssh-keys}:/root/.ssh
      - ./config/db/firebird/2.5/firebird.conf:/opt/firebird/firebird.conf
    command: sh /run.sh
    networks:
      - damabox
    depends_on:
      - bind

  firebird-3.0:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-firebird3.0
    restart: always
    dns:
      - ${BIND_IP:-10.5.0.10}
    hostname: firebird-3.0
    ports:
      - ${FIREBIRD30_PORT:-3051}:3050
      - ${HQBIRD30_PANEL_PORT:-8083}:8082
      - ${HQBIRD30_LICENSE_PORT:-8766}:8765
    environment:
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${FIREBIRD30_DATA_DIR:-./data/db/firebird/3.0}:/databases
      - ${SSH_KEYS:-./data/ssh-keys}:/root/.ssh
      - ./config/db/firebird/3.0/firebird.conf:/opt/firebird/firebird.conf
    command: sh /run.sh
    networks:
      - damabox
    depends_on:
      - bind
